In [ ]:
# This file is used to merge data record of crashed by year interval into one dataset
# This version of merged dataset is not used for the project

In [1]:
# pip install openpyxl

In [55]:
import pandas as pd

In [56]:
y1213 = pd.read_csv("1213.csv",dtype = {0 : "string"})
y1420 = pd.read_csv("1420.csv",dtype = {0 : "string"})
y2021 = pd.read_excel("2021.xlsx",dtype = {0 : "string"})

In [57]:
y2022 = pd.read_excel("2022.xlsx",dtype = {0 : "string"})
y2023 = pd.read_csv("2023.csv",dtype = {0 : "string"})
y2024 = pd.read_excel("2024.xlsx",dtype = {0 : "string"})

In [58]:
y1213f = y1213.columns.tolist()
y1420f = y1420.columns.tolist()
y2021f = y2021.columns.tolist()
y2022f = y2022.columns.tolist()
y2023f = y2023.columns.tolist()
y2024f = y2024.columns.tolist()
yflist = [y1213f,y1420f,y2021f,y2022f,y2023f,y2024f]

In [61]:
def check(l):
    isid = 1
    names = ["1213", "1420", "2021", "2022", "2023", "2024"]
    for i in range (len(l)-1):
        base = l[i]
        for j in range (i+1 , len(l)):
            if l[j] != base:
                isid = 0
                print(f"{names[i]} != {names[j]}")
    if isid == 1:
        print("all equal")

In [62]:
check(yflist)

1213 != 2024
1420 != 2024
2021 != 2024
2022 != 2024
2023 != 2024

In [63]:
unmatched_2024 = sorted(set(y2024f) - set(y1213f))
unmatched_base = sorted(set(y1213f) - set(y2024f))
print(unmatched_2024, unmatched_base)

['CityTownNa', 'ClosestCro', 'CollisionT', 'Commercial', 'CrashSever', 'DMVInsertD', 'DirectionF', 'DistanceFr', 'Extra columns', 'Intersecti', 'Lat', 'LightCondi', 'Long', 'MAINT_JURI', 'MasterInte', 'MaxInjuryS', 'NonPublicW', 'NonReporta', 'NumberOfFa', 'NumberOfIn', 'NumberOfOt', 'NumberOfSe', 'NumberOfVe', 'OBJECTID', 'OWNING_JUR', 'ReferenceM', 'ReportingA', 'RoadSurfac', 'RoadwayAcc', 'RoadwayCha', 'TrafficCon', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'WeatherCon'] ['CityTownName', 'ClosestCrossStreet', 'CommercialVehicleCrashInd', 'CrashSeverity', 'CrashTime', 'CrashTypeCde', 'DMVInsertDate', 'DirectionFromIntersection', 'DistanceFromIntersection', 'IntersectionIndicator', 'LightCondition', 'MAINT_JURISDICTION_TYPE_ID', 'MasterIntersectionId', 'MaxInjurySeverity', 'NonPublicWayCode', 'NonReportable', 'NumberOfFatalities', 'NumberOfInjuries', 'NumberOfOtherInjuries', 'NumberOfSeriousInjuries', 'NumberOfVehicles', 'OWNING_JURISDICTION_TYPE_ID', 'ReferenceMarker', 'ReportingAgency', 'RoadSurfaceCondition', 'RoadwayAccessControlCde', 'RoadwayCharacteristic', 'TrafficControl', 'WeatherCondition']

In [64]:
import difflib

base_cols = y1213.columns.tolist()
y24_cols  = y2024.columns.tolist()

base_set = set(base_cols)

rn_map = {}

for f in y24_cols:
    if f in base_set:
        continue 
    matches = difflib.get_close_matches(f, base_cols, n=1, cutoff = 0.6)
    if matches:
        rn_map[f] = matches[0]

In [69]:
rename_map = {
    'MaxInjuryS': 'MaxInjurySeverity',
    'CrashSever': 'CrashSeverity',
    'RoadwayAcc': 'RoadwayAccessControlCde',
    'LightCondi': 'LightCondition',
    'RoadwayCha': 'RoadwayCharacteristic',
    'RoadSurfac': 'RoadSurfaceCondition',
    'TrafficCon': 'TrafficControl',
    'WeatherCon': 'WeatherCondition',
    'Commercial': 'CommercialVehicleCrashInd',
    'DMVInsertD': 'DMVInsertDate',
    'NumberOfFa': 'NumberOfFatalities',
    'NumberOfIn': 'NumberOfInjuries',
    'NumberOfOt': 'NumberOfOtherInjuries',
    'NumberOfSe': 'NumberOfSeriousInjuries',
    'NumberOfVe': 'NumberOfVehicles',
    'NonReporta': 'NonReportable',
    'ReportingA': 'ReportingAgency',
    'NonPublicW': 'NonPublicWayCode',
    'ClosestCro': 'ClosestCrossStreet',
    'MasterInte': 'MasterIntersectionId',
    'Intersecti': 'IntersectionIndicator',
    'CityTownNa': 'CityTownName',
    'ReferenceM': 'ReferenceMarker',
    'MAINT_JURI': 'MAINT_JURISDICTION_TYPE_ID',
    'OWNING_JUR': 'OWNING_JURISDICTION_TYPE_ID',
    'DirectionF': 'DirectionFromIntersection',
    'DistanceFr': 'DistanceFromIntersection'
}

In [70]:
y2024_new = y2024.copy().rename(columns = rename_map)
y2024f_new = y2024_new.columns.tolist()

In [99]:
yflist2 = [y1213f,y1420f,y2021f,y2022f,y2023f,y2024f_new]
check(yflist2)

1213 != 2024
1420 != 2024
2021 != 2024
2022 != 2024
2023 != 2024

In [100]:
unmatched_2024_new = sorted(set(y2024f_new) - set(y1213f))
unmatched_base = sorted(set(y1213f) - set(y2024f_new))
print(unmatched_2024_new, unmatched_base)

['CollisionT', 'Extra columns', 'Lat', 'Long', 'OBJECTID', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49'] ['CrashTime', 'CrashTypeCde']

In [101]:
drop_2024 = ['Extra columns', 'Lat', 'Long', 'OBJECTID', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49','CollisionT']
y2024_new_d = y2024_new.copy().drop(columns = drop_2024)

In [102]:
# y2024f_new_d = y2024_new_d.columns.tolist()
# unmatched_2024_new_d = sorted(set(y2024f_new_d) - set(y1213f))
# unmatched_base = sorted(set(y1213f) - set(y2024f_new_d))
# print(unmatched_2024_new_d, unmatched_base)

In [103]:
y2024_new_d["CrashDate"] = pd.to_datetime(y2024_new_d["CrashDate"], errors="coerce").dt.date

In [104]:
dflist = [y1213,y1420,y2021,y2022,y2023,y2024_new_d]
result = pd.concat(dflist, ignore_index=True)

In [105]:
result

,CaseNumber,CaseYear,CrashDate,CrashTime,CrashTimeFormatted,CrashTypeCde,CrashType,CollisionType,CrashSeverity,LightCondition,...,isLargeTruckCrash,DriverAgeVehicleOne,DriverAgeVehicleTwo,DriverAgeVehicleThree,DriverAgeVehicleFour,DriverAgeVehicleFive,PersonTypes,PersonInjuries,ApparentFactors,ApparentFactorCodes
0,34164055,2012,01/04/2012,1113.0,11:13 AM,1.0,COLLISION WITH MOTOR VEHICLE,OTHER,PROPERTY DAMAGE,DAYLIGHT,...,0,19.0,0.0,0.0,NaN,NaN,U1:(DRIVER) / U2:(DRIVER) / U3:(DRIVER),U1:(U - UNKNOWN) / U2:(U - UNKNOWN) / U3:(U - ...,"V1:(DRIVER INATTENTION,FOLLOWING TOO CLOSELY) ...",|4|9|777|777|777|777|
1,34164075,2012,01/03/2012,1145.0,11:45 AM,1.0,COLLISION WITH MOTOR VEHICLE,RIGHT ANGLE,PROPERTY DAMAGE,DAYLIGHT,...,0,60.0,0.0,NaN,NaN,NaN,U1:(DRIVER) / U2:(DRIVER),U1:(U - UNKNOWN) / U2:(U - UNKNOWN),"V1:(FOLLOWING TOO CLOSELY,DRIVER INATTENTION) ...",|9|4|777|777|
2,34164104,2012,01/07/2012,2130.0,9:30 PM,7.0,COLLISION WITH DEER,OTHER,PROPERTY DAMAGE,DARK-ROAD UNLIGHTED,...,0,22.0,NaN,NaN,NaN,NaN,U1:(DRIVER),U1:(U - UNKNOWN),"V1:(ANIMALS ACTION,NOT APPLICABLE)",|61|777|
3,34164105,2012,01/08/2012,1842.0,6:42 PM,1.0,COLLISION WITH MOTOR VEHICLE,RIGHT ANGLE,INJURY,DARK-ROAD LIGHTED,...,0,31.0,0.0,NaN,NaN,NaN,U1:(DRIVER) / U2:(DRIVER),U1:(U - UNKNOWN) / U2:(U - UNKNOWN),"V1:(NOT APPLICABLE,NOT APPLICABLE) / V2:(TRAFF...",|777|777|17|7|
4,34164107,2012,01/04/2012,1804.0,6:04 PM,23.0,COLL. W/EARTH ELE./ROCK CUT/DITCH,OTHER,PROPERTY DAMAGE,DARK-ROAD UNLIGHTED,...,0,22.0,NaN,NaN,NaN,NaN,U1:(DRIVER),U1:(U - UNKNOWN),"V1:(UNSAFE SPEED,DRIVER INATTENTION)",|19|4|
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291629,40826635,2024,2024-04-04,NaN,16:23:00,NaN,COLLISION WITH MOTOR VEHICLE,REAR END,PROPERTY DAMAGE,DAYLIGHT,...,0,64.0,NaN,NaN,NaN,NaN,U1:(DRIVER) / U2:(INVALID CODE),U1:(U - UNKNOWN) / U2:(U - UNKNOWN),"V1:(TURNING IMPROPER,NOT APPLICABLE) / V2:(NOT...",|18|777|777|777|
291630,40826645,2024,2024-04-04,NaN,15:26:00,NaN,COLLISION WITH MOTOR VEHICLE,RIGHT ANGLE,PROPERTY DAMAGE,DAYLIGHT,...,0,29.0,0.0,NaN,NaN,NaN,U1:(DRIVER) / U2:(DRIVER),U1:(U - UNKNOWN) / U2:(U - UNKNOWN),"V1:(PASSING OR LANE USAGE IMPROPERLY,NOT APPLI...",|13|777|777|777|
291631,40827434,2024,2024-10-04,NaN,16:19:00,NaN,COLLISION WITH MOTOR VEHICLE,LEFT TURN (AGAINST OTHER CAR),PROPERTY DAMAGE,DAYLIGHT,...,0,19.0,0.0,NaN,NaN,NaN,U1:(DRIVER) / U2:(DRIVER) / U2:(PASSENGER),U1:(U - UNKNOWN) / U2:(U - UNKNOWN) / U2:(U - ...,"V1:(TRAFFIC CONTROL DEVICES DISREGARDED,NOT AP...",|17|777|777|777|
291632,40829615,2024,2024-06-13,NaN,17:45:00,NaN,COLLISION WITH OTHER BARRIER,OTHER,PROPERTY DAMAGE,DAYLIGHT,...,0,70.0,NaN,NaN,NaN,NaN,U1:(DRIVER),U1:(U - UNKNOWN),"V1:(DRIVER INATTENTION,NOT APPLICABLE)",|4|777|
291633,40839728,2024,2024-04-12,NaN,04:40:00,NaN,COLLISION WITH MOTOR VEHICLE,REAR END,PROPERTY DAMAGE,DARK-ROAD LIGHTED,...,0,NaN,0.0,NaN,NaN,NaN,U2:(DRIVER),U2:(U - UNKNOWN),"V1:(DRIVER INATTENTION,UNKNOWN) / V2:(NOT APPL...",|4|999|777|777|

In [106]:
result = result.drop(columns = ['CrashTime','CrashTypeCde','ApparentFactorCodes'])

In [107]:
result["CrashDate"] = pd.to_datetime(result["CrashDate"], errors="coerce").dt.date

In [108]:
result["IntersectionIndicator"] = (
    pd.to_numeric(result["IntersectionIndicator"], errors="coerce")
    .astype("Int64") 
    .astype("string")
)

In [109]:
result["IntersectionIndicator"]

0         0
1         0
2         0
3         2
4         2
         ..
291629    0
291630    2
291631    1
291632    0
291633    2
Name: IntersectionIndicator, Length: 291634, dtype: string

In [110]:
result.columns

Index(['CaseNumber', 'CaseYear', 'CrashDate', 'CrashTimeFormatted',
       'CrashType', 'CollisionType', 'CrashSeverity', 'LightCondition',
       'WeatherCondition', 'RoadwayAccessControlCde', 'RoadwayCharacteristic',
       'RoadSurfaceCondition', 'TrafficControl', 'TrafficWay',
       'MaxInjurySeverity', 'NumberOfFatalities', 'NumberOfInjuries',
       'NumberOfSeriousInjuries', 'NumberOfOtherInjuries', 'NumberOfVehicles',
       'PoliceDept', 'ReportingAgency', 'Precinct',
       'CommercialVehicleCrashInd', 'PPDRCode', 'NonReportable',
       'ReviewedIndicator', 'DMVInsertDate', 'CountyFIPS', 'CountyName',
       'MuniFIPS', 'CityTownName', 'OnStreet', 'ClosestCrossStreet',
       'MasterIntersectionId', 'IntersectionIndicator', 'ReferenceMarker',
       'DistanceFromIntersection', 'DirectionFromIntersection', 'UTMEasting',
       'UTMNorthing', 'NonPublicWayCode', 'ACCESS_CONTROL', 'DIVIDED',
       'FUNCTIONAL_CLASS', 'MAINT_JURISDICTION_TYPE_ID',
       'OWNING_JURISDICTION_TYPE_ID', 'NAME', 'POSTED_SPEED', 'VehicleTypes',
       'VehicleBodyTypes', 'CommercialVehicles', 'PreCrashActions',
       'isLargeTruckCrash', 'DriverAgeVehicleOne', 'DriverAgeVehicleTwo',
       'DriverAgeVehicleThree', 'DriverAgeVehicleFour', 'DriverAgeVehicleFive',
       'PersonTypes', 'PersonInjuries', 'ApparentFactors'],
      dtype='object')

In [111]:
print(len(result.columns.tolist()))

62

In [112]:
na_tokens = ["", " ", "  ", "\t", "\n", "NULL", "null", "NaN", "nan", "N/A", "n/a", "NA", "na"]
result = result.replace(na_tokens, pd.NA)

In [113]:
col_s = result.select_dtypes(include=["object", "string"]).columns

for col in col_s:
    result[col] = (result[col].astype("string").str.strip().str.replace(r"\s+", " ", regex = True).str.title())

In [114]:
result

,CaseNumber,CaseYear,CrashDate,CrashTimeFormatted,CrashType,CollisionType,CrashSeverity,LightCondition,WeatherCondition,RoadwayAccessControlCde,...,PreCrashActions,isLargeTruckCrash,DriverAgeVehicleOne,DriverAgeVehicleTwo,DriverAgeVehicleThree,DriverAgeVehicleFour,DriverAgeVehicleFive,PersonTypes,PersonInjuries,ApparentFactors
0,34164055,2012,2012-01-04,11:13 Am,Collision With Motor Vehicle,Other,Property Damage,Daylight,Cloudy,999.0,...,V1:(Slowed Or Stopping) V2:(Stopped In Traffic...,0,19.0,0.0,0.0,NaN,NaN,U1:(Driver) / U2:(Driver) / U3:(Driver),U1:(U - Unknown) / U2:(U - Unknown) / U3:(U - ...,"V1:(Driver Inattention,Following Too Closely) ..."
1,34164075,2012,2012-01-03,11:45 Am,Collision With Motor Vehicle,Right Angle,Property Damage,Daylight,Clear,999.0,...,V1:(Slowed Or Stopping) V2:(Going Straight Ahead),0,60.0,0.0,NaN,NaN,NaN,U1:(Driver) / U2:(Driver),U1:(U - Unknown) / U2:(U - Unknown),"V1:(Following Too Closely,Driver Inattention) ..."
2,34164104,2012,2012-01-07,9:30 Pm,Collision With Deer,Other,Property Damage,Dark-Road Unlighted,Cloudy,999.0,...,V1:(Going Straight Ahead),0,22.0,NaN,NaN,NaN,NaN,U1:(Driver),U1:(U - Unknown),"V1:(Animals Action,Not Applicable)"
3,34164105,2012,2012-01-08,6:42 Pm,Collision With Motor Vehicle,Right Angle,Injury,Dark-Road Lighted,Clear,999.0,...,V1:(Going Straight Ahead) V2:(Going Straight A...,0,31.0,0.0,NaN,NaN,NaN,U1:(Driver) / U2:(Driver),U1:(U - Unknown) / U2:(U - Unknown),"V1:(Not Applicable,Not Applicable) / V2:(Traff..."
4,34164107,2012,2012-01-04,6:04 Pm,Coll. W/Earth Ele./Rock Cut/Ditch,Other,Property Damage,Dark-Road Unlighted,Cloudy,999.0,...,V1:(Going Straight Ahead),0,22.0,NaN,NaN,NaN,NaN,U1:(Driver),U1:(U - Unknown),"V1:(Unsafe Speed,Driver Inattention)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291629,40826635,2024,2024-04-04,16:23:00,Collision With Motor Vehicle,Rear End,Property Damage,Daylight,Rain,999.0,...,V1:(Backing) V2:(Parked),0,64.0,NaN,NaN,NaN,NaN,U1:(Driver) / U2:(Invalid Code),U1:(U - Unknown) / U2:(U - Unknown),"V1:(Turning Improper,Not Applicable) / V2:(Not..."
291630,40826645,2024,2024-04-04,15:26:00,Collision With Motor Vehicle,Right Angle,Property Damage,Daylight,Rain,999.0,...,V1:(Going Straight Ahead) V2:(Starting In Traf...,0,29.0,0.0,NaN,NaN,NaN,U1:(Driver) / U2:(Driver),U1:(U - Unknown) / U2:(U - Unknown),"V1:(Passing Or Lane Usage Improperly,Not Appli..."
291631,40827434,2024,2024-10-04,16:19:00,Collision With Motor Vehicle,Left Turn (Against Other Car),Property Damage,Daylight,Clear,999.0,...,V1:(Going Straight Ahead) V2:(Making Left Turn),0,19.0,0.0,NaN,NaN,NaN,U1:(Driver) / U2:(Driver) / U2:(Passenger),U1:(U - Unknown) / U2:(U - Unknown) / U2:(U - ...,"V1:(Traffic Control Devices Disregarded,Not Ap..."
291632,40829615,2024,2024-06-13,17:45:00,Collision With Other Barrier,Other,Property Damage,Daylight,Clear,999.0,...,V1:(Going Straight Ahead),0,70.0,NaN,NaN,NaN,NaN,U1:(Driver),U1:(U - Unknown),"V1:(Driver Inattention,Not Applicable)"
291633,40839728,2024,2024-04-12,04:40:00,Collision With Motor Vehicle,Rear End,Property Damage,Dark-Road Lighted,Rain,999.0,...,V1:(Going Straight Ahead) V2:(Stopped In Traffic),0,NaN,0.0,NaN,NaN,NaN,U2:(Driver),U2:(U - Unknown),"V1:(Driver Inattention,Unknown) / V2:(Not Appl..."

In [115]:
result.to_csv("merged.csv", index=False)

In [ ]:
report_features = [
    "CrashDate",
    "CrashTimeFormatted",
    "UTMEasting",
    "UTMNorthing",
    "CityTownName",
    "IntersectionIndicator",
    "OnStreet",              
    "ClosestCrossStreet",   
    "CrashSeverity",         
    "NumberOfFatalities",
    "NumberOfSeriousInjuries",
    "NumberOfInjuries",
    "NumberOfOtherInjuries",
    "CrashType",
    "CollisionType",
    "LightCondition",
    "WeatherCondition",
    "RoadSurfaceCondition",
    "TrafficControl",
    "TrafficWay",
    "RoadwayCharacteristic",
    "FUNCTIONAL_CLASS",
    "DIVIDED",
    "ACCESS_CONTROL",      
    "POSTED_SPEED",
    "NumberOfVehicles",
    "CommercialVehicleCrashInd",
    "isLargeTruckCrash"]